-- tag::adocSQL[]
INSERT INTO advice(id,concept, description, advice, url)
VALUES (nextval('hibernate_sequence'), 'Depósito bancario', 'Productos de ahorro que ofrecen rentabilidad sin asumir riesgos.', 'El depósito Online de BBVA es una opción interesante si lo que quieres es guardar tus ahorros sin que te cobren: este producto está libre de comisiones de apertura o mantenimiento, unos costes que sí cobran algunas cuentas bancarias', 'https://bbva.es/general/diccionario-economico/d/deposito-bancario');
INSERT INTO advice(id,concept, description, advice, url)
VALUES (nextval('hibernate_sequence'), 'Pŕestamo personal', 'Producto bancario por la que el banco pone a disposición de quien lo solicita una determinada cantidad de dinero con unas condiciones estipuladas relativas a plazos, cuotas, intereses, etc','El préstamo personal Online del banco BBVA permite obtener hasta 75.000 euros a devolver en un máximo de 8 años y para utilizar en lo que más se necesite','https://bbva.es/general/diccionario-economico/p/prestamo-personal');
INSERT INTO advice(id,concept, description, advice, url)
VALUES (nextval('hibernate_sequence'), 'Renta vitalicia', 'Tipo de seguro de vida en el que el asegurado paga una prima única a la compañía de seguros, y a cambio recibe una cantidad de dinero periódica garantizada hasta el momento de su fallecimiento', 'Si lo contratas con BBVA se garantiza una seguridad y certidumbre,  en relación a la garantía que ofrecen, en un contexto de notable volatilidad y fluctuación en los mercados financieros.', 'https://www.bbva.es/finanzas-vistazo/ef/seguros/seguro-renta-vitalicia.html');
INSERT INTO advice(id,concept, description, advice, url)
VALUES (nextval('hibernate_sequence'), 'Seguro de coche', 'Seguro cuyo objeto es asegurar los riesgos relacionados con un vehículo y sus ocupantes', 'Con los seguros de coche de BBVA dispones de una amplia gama de modalidades para que lo adaptes a tus necesidades', 'https://www.bbva.es/diccionario-economico/s/seguro-de-coche.html');
INSERT INTO advice(id,concept, description, advice, url)
VALUES (nextval('hibernate_sequence'), 'Tarjeta de crédito', 'Medio de pago cuyo uso permite aplazar el pago del importe de la operación en la cuenta bancaria asociada a la tarjeta', 'En BBVA existe la Tarjeta Después Oro BBVA con la que puedes pagar aunque no tengas dinero en tu cuenta, devolviendo el dinero en la modalidad que prefieras', 'https://www.bbva.es/diccionario-economico/t/tarjeta-de-credito.html');
INSERT INTO advice(id,concept, description, advice, url)
VALUES (nextval('hibernate_sequence'), 'Hipoteca', 'Derecho real que grava un bien inmueble y que normalmente se utiliza para lograr la financiación necesaria para su compra', 'Con la Hipoteca Fija BBVA paga la misma cuota todos los meses, sin sorpresas. Entra en bbva.es e infórmate de nuestra hipoteca a tipo fijo', 'https://www.bbva.es/diccionario-economico/h/hipoteca.html');
INSERT INTO advice(id,concept, description, advice, url)
VALUES (nextval('hibernate_sequence'), 'Bolsa de valores', 'Mercado organizado en el que se negocian operaciones de compraventa de títulos valores', 'El servicio BBVA Bolsa Broker te ofrece una de las mejores tarifas de BBVA para invertir a través de bbva.es y nuestra app, en acciones o ETF cotizados en la bolsa española', 'https://www.bbva.es/diccionario-economico/b/bolsa-de-valores.html');
INSERT INTO advice(id,concept, description, advice, url)
VALUES (nextval('hibernate_sequence'), 'Fondo de inversión', 'Producto financiero que permite a los inversores realizar aportaciones de capital con el principal objetivo de rentabilizar sus ahorros', 'El fondo de inversión BBVA Consolidación 85 tiene capacidad de captar rentabilidad con un riesgo moderado', 'https://www.bbva.es/diccionario-economico/f/fondo-de-inversion.html');
INSERT INTO advice(id,concept, description, advice, url)
VALUES (nextval('hibernate_sequence'), 'Plan de pensiones', 'Producto financiero de inversión y ahorro al cual hacemos aportaciones periódicas o puntuales que en el futuro nos permitirán disponer de un capital o renta como complemento a nuestra pensión de jubilación', ' El que obtuvo mayor rentabilidad en los últimos 12 meses fue BBVA Telecomunicaciones, uno de los mejores en renta variable en todo el mercado español.', 'https://www.bbva.es/diccionario-economico/p/plan-de-pensiones.html');
INSERT INTO advice(id,concept, description, advice, url)
VALUES (nextval('hibernate_sequence'), 'ICO', 'Entidad pública empresarial cuyo objetivo es promover las actividades económicas que contribuyan al crecimiento y a la mejora de la distribución de la riqueza nacional ', ' En BBVA queremos ayudarte a reducir el impacto del coronavirus en tu negocio. Si tienes una empresa o eres autónomo, puedes beneficiarte de la financiación que ofrecemos y que se apoya en las líneas de avales del Estado gestionada por el ICO.', 'https://www.bbva.es/diccionario-economico/i/ico.html');
-- end::adocSQL[]
